### ISSUE TITLE
Trying to use the agent jar failing with missing manifest or missing jar warnings

### ISSUE THREAD

**Issue by aptmac** [aptmac/jmc-agent#4]
Not sure if it's something I did, but out of the box the agent.jar isn't working when using the CLI and the agent plugin.

When trying to run the agent demonstration from the CLI:
```
Error opening zip file or JAR manifest missing : target/org.openjdk.jmc.agent-1.0.1-SNAPSHOT.jar
```

When trying to attach the agent jar to the JMC Agent Plugin:
```
com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:159)
	at org.openjdk.jmc.console.agent.wizards.StartAgentWizard.loadAgent(StartAgentWizard.java:122)
	at org.openjdk.jmc.console.agent.wizards.StartAgentWizard.performFinish(StartAgentWizard.java:83)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
[..]
```

**Comment by aptmac** [comment]
Looks like it's the permissions on my agent jar.

**Comment by aptmac** [comment]
> Looks like it's the permissions on my agent jar.

Not quite. It really needed the maven-shade-plugin, which is available in Fedora from f34 onward.

Fixed in: https://github.com/aptmac/jmc-agent/commit/c0ca6c7ca51e397e8955d002350937d2c5b82241
